# Generated by Django 4.2.23 on 2025-07-25 04:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('statuses', models.JSONField(blank=True, default=list, null=True)),
                ('priorities', models.JSONField(blank=True, default=list, null=True)),
                ('billable', models.BooleanField(default=False)),
                ('deadline', models.BigIntegerField(blank=True, help_text='Date in milliseconds when project must be done', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employees', models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
