# Generated by Django 4.2.23 on 2025-07-25 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('time_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Path to the screenshot file', max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('permissions_granted', models.BooleanField(default=False, help_text='Whether screen recording permissions were granted')),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to=settings.AUTH_USER_MODEL)),
                ('time_tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='time_tracking.timetracking')),
            ],
        ),
    ]
