# Generated by Django 4.2.23 on 2025-07-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetracking',
            name='device_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='time_offset',
            field=models.IntegerField(blank=True, help_text='Offset from UTC in milliseconds', null=True),
        ),
    ]
