# Generated by Django 4.2.23 on 2025-07-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0002_timetracking_device_details_timetracking_time_offset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetracking',
            name='time_offset',
        ),
        migrations.AddField(
            model_name='timetracking',
            name='timezone',
            field=models.CharField(blank=True, help_text='Timezone name, e.g. Asia/Kolkata', max_length=64, null=True),
        ),
    ]
