# Generated by Django 4.2.23 on 2025-07-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracking', '0003_remove_timetracking_time_offset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetracking',
            name='last_heart_beat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
